### ISSUE TITLE
Dice Loss

### ISSUE THREAD

**Issue by RockMan1966** [xiaofang007/CTO#3]
作者你好，您提供的代码 边缘损失Dice Loss 我运行得到的是负值，请问这种情况是正常情况吗

**Comment by xiaofang007** [comment]
您好，参考MedISeg/unet2d/NetworkTrainer/utils/losses_imbalance.py DiceLoss而且我又用ISIC-2018数据库跑了几遍发现我的loss都是在(0,1)，我认为这种情况不正常
