### ISSUE TITLE
Requesting source code for another article from your team

### ISSUE THREAD

**Issue by WangBJ233** [xiaofang007/CTO#6]
Hello author, thank you very much for your outstanding work!
I learned that the article Few Shot Medical Image Segmentation with Cross Attention Transformer on arXiv was also published by your team. The abstract of Few Shot Medical Image Segmentation with Cross Attention Transformer states that the source code will be released if the article is accepted. When will you release the source code for this article? 
I look forward to hearing from you!

**Comment by xiaofang007** [comment]
Hi, the code will be published here: https://github.com/hust-linyi/CAT-Net
