### ISSUE TITLE
FileNotFoundError:[Errno 2lNo such file orirectory:'/root/autodl-tmp/CT0/ISIC2018/aug/img.npy

### ISSUE THREAD

**Issue by ZMTangYan** [xiaofang007/CTO#9]
Hello, I'm in training when the error: FileNotFoundError: '/ root/autodl - / TMP/CT0 ISIC2018 / aug/img. Npy. I can't find the file /aug/img.npy. It seems that I can't find the code related to aug when I look for the code. Could you please share it? Thank you very much!

**Comment by xiaofang007** [comment]
Hi, sorry for the confusion, you can comment out this line. We do not use GAN-related augmentation in this paper and you might refer to get_transform.py in MedISeg framework to try other data preprocessing methods.
